export const UI = {
    AUTH: {
        LOGIN: {
            TITLE: 'Đăng nhập',
            SUBTITLE: 'Chào mừng trở lại',
            EMAIL_LABEL: 'Email',
            EMAIL_PLACEHOLDER: 'Nhập email của bạn',
            PASSWORD_LABEL: 'Mật khẩu',
            PASSWORD_PLACEHOLDER: 'Nhập mật khẩu',
            LOADING_TEXT: 'Đang đăng nhập...',
            SUBMIT_TEXT: 'Đăng nhập',
            FORGOT_PASSWORD: 'Quên mật khẩu?',
            NO_ACCOUNT: 'Chưa có tài khoản?',
            REGISTER_LINK: 'Đăng ký ngay',
            REMEMBER_ME: 'Ghi nhớ đăng nhập',
            OR_DIVIDER: 'Hoặc',
            SOCIAL_LOGIN: 'Đăng nhập bằng',
            GOOGLE_LOGIN: 'Đăng nhập với Google',
            FACEBOOK_LOGIN: 'Đăng nhập với Facebook',
        },

        REGISTER: {
            TITLE: 'Đăng ký',
            SUBTITLE: 'Tạo tài khoản mới',
            FIRST_NAME_LABEL: 'Họ',
            LAST_NAME_LABEL: 'Tên',
            FULL_NAME_LABEL: 'Họ và tên',
            EMAIL_LABEL: 'Email',
            EMAIL_PLACEHOLDER: 'Nhập email của bạn',
            PASSWORD_LABEL: 'Mật khẩu',
            PASSWORD_PLACEHOLDER: 'Tạo mật khẩu',
            CONFIRM_PASSWORD_LABEL: 'Xác nhận mật khẩu',
            CONFIRM_PASSWORD_PLACEHOLDER: 'Nhập lại mật khẩu',
            PHONE_LABEL: 'Số điện thoại',
            PHONE_PLACEHOLDER: 'Nhập số điện thoại',
            LOADING_TEXT: 'Đang đăng ký...',
            SUBMIT_TEXT: 'Đăng ký',
            HAVE_ACCOUNT: 'Đã có tài khoản?',
            LOGIN_LINK: 'Đăng nhập ngay',
            TERMS_AGREEMENT: 'Tôi đồng ý với',
            TERMS_OF_SERVICE: 'Điều khoản dịch vụ',
            PRIVACY_POLICY: 'Chính sách bảo mật',
            AND: 'và',
        },

        FORGOT_PASSWORD: {
            TITLE: 'Quên mật khẩu',
            SUBTITLE: 'Nhập email để đặt lại mật khẩu',
            EMAIL_LABEL: 'Email',
            EMAIL_PLACEHOLDER: 'Nhập email của bạn',
            SUBMIT_TEXT: 'Gửi link đặt lại',
            LOADING_TEXT: 'Đang gửi...',
            BACK_TO_LOGIN: 'Quay lại đăng nhập',
            CHECK_EMAIL: 'Kiểm tra email của bạn',
            RESEND_EMAIL: 'Gửi lại email',
        },

        RESET_PASSWORD: {
            TITLE: 'Đặt lại mật khẩu',
            SUBTITLE: 'Tạo mật khẩu mới',
            NEW_PASSWORD_LABEL: 'Mật khẩu mới',
            CONFIRM_PASSWORD_LABEL: 'Xác nhận mật khẩu mới',
            SUBMIT_TEXT: 'Đặt lại mật khẩu',
            LOADING_TEXT: 'Đang đặt lại...',
            SUCCESS_MESSAGE: 'Mật khẩu đã được đặt lại thành công',
            CONTINUE_TO_LOGIN: 'Tiếp tục đăng nhập',
        },

        LOGOUT: {
            CONFIRM_TITLE: 'Xác nhận đăng xuất',
            CONFIRM_MESSAGE: 'Bạn có chắc chắn muốn đăng xuất?',
            CONFIRM_BUTTON: 'Đăng xuất',
            CANCEL_BUTTON: 'Hủy',
        },
    },

    // Profile UI Text
    PROFILE: {
        TITLE: 'Thông tin cá nhân',
        EDIT_PROFILE: 'Chỉnh sửa hồ sơ',
        VIEW_PROFILE: 'Xem hồ sơ',

        PERSONAL_INFO: {
            TITLE: 'Thông tin cá nhân',
            FULL_NAME_LABEL: 'Họ và tên',
            EMAIL_LABEL: 'Email',
            PHONE_LABEL: 'Số điện thoại',
            DATE_OF_BIRTH_LABEL: 'Ngày sinh',
            GENDER_LABEL: 'Giới tính',
            ADDRESS_LABEL: 'Địa chỉ',
            BIO_LABEL: 'Giới thiệu',
            AVATAR_LABEL: 'Ảnh đại diện',
            UPLOAD_AVATAR: 'Tải ảnh lên',
            CHANGE_AVATAR: 'Thay đổi ảnh',
            REMOVE_AVATAR: 'Xóa ảnh',
        },

        SECURITY: {
            TITLE: 'Bảo mật',
            CHANGE_PASSWORD: 'Đổi mật khẩu',
            CURRENT_PASSWORD_LABEL: 'Mật khẩu hiện tại',
            NEW_PASSWORD_LABEL: 'Mật khẩu mới',
            CONFIRM_PASSWORD_LABEL: 'Xác nhận mật khẩu mới',
            TWO_FACTOR_AUTH: 'Xác thực hai yếu tố',
            ENABLE_2FA: 'Bật 2FA',
            DISABLE_2FA: 'Tắt 2FA',
            LOGIN_HISTORY: 'Lịch sử đăng nhập',
            ACTIVE_SESSIONS: 'Phiên đăng nhập',
            TERMINATE_SESSION: 'Kết thúc phiên',
        },

        PREFERENCES: {
            TITLE: 'Tùy chọn',
            LANGUAGE: 'Ngôn ngữ',
            THEME: 'Giao diện',
            LIGHT_THEME: 'Sáng',
            DARK_THEME: 'Tối',
            AUTO_THEME: 'Tự động',
            NOTIFICATIONS: 'Thông báo',
            EMAIL_NOTIFICATIONS: 'Thông báo qua email',
            PUSH_NOTIFICATIONS: 'Thông báo đẩy',
            SMS_NOTIFICATIONS: 'Thông báo SMS',
        },

        DANGER_ZONE: {
            TITLE: 'Vùng nguy hiểm',
            DELETE_ACCOUNT: 'Xóa tài khoản',
            DELETE_CONFIRMATION: 'Xóa tài khoản vĩnh viễn',
            DELETE_WARNING: 'Hành động này không thể hoàn tác',
            TYPE_TO_CONFIRM: 'Nhập "XÓA" để xác nhận',
        },
    },

    // Product UI Text
    PRODUCT: {
        TITLE: 'Sản phẩm',
        ADD_PRODUCT: 'Thêm sản phẩm',
        EDIT_PRODUCT: 'Chỉnh sửa sản phẩm',
        PRODUCT_DETAILS: 'Chi tiết sản phẩm',
        PRODUCT_LIST: 'Danh sách sản phẩm',

        FORM: {
            NAME_LABEL: 'Tên sản phẩm',
            NAME_PLACEHOLDER: 'Nhập tên sản phẩm',
            DESCRIPTION_LABEL: 'Mô tả',
            DESCRIPTION_PLACEHOLDER: 'Mô tả chi tiết sản phẩm',
            PRICE_LABEL: 'Giá',
            PRICE_PLACEHOLDER: 'Nhập giá sản phẩm',
            CATEGORY_LABEL: 'Danh mục',
            CATEGORY_PLACEHOLDER: 'Chọn danh mục',
            BRAND_LABEL: 'Thương hiệu',
            STOCK_LABEL: 'Số lượng tồn kho',
            SKU_LABEL: 'Mã sản phẩm (SKU)',
            TAGS_LABEL: 'Thẻ tag',
            IMAGES_LABEL: 'Hình ảnh',
            UPLOAD_IMAGES: 'Tải ảnh lên',
            STATUS_LABEL: 'Trạng thái',
            FEATURED_LABEL: 'Sản phẩm nổi bật',
        },

        STATUS: {
            ACTIVE: 'Hoạt động',
            INACTIVE: 'Không hoạt động',
            DRAFT: 'Bản nháp',
            OUT_OF_STOCK: 'Hết hàng',
            DISCONTINUED: 'Ngừng kinh doanh',
        },

        CART: {
            ADD_TO_CART: 'Thêm vào giỏ',
            BUY_NOW: 'Mua ngay',
            QUANTITY: 'Số lượng',
            SUBTOTAL: 'Tạm tính',
            TOTAL: 'Tổng cộng',
            CHECKOUT: 'Thanh toán',
            CONTINUE_SHOPPING: 'Tiếp tục mua sắm',
            CART_EMPTY: 'Giỏ hàng trống',
            GO_SHOPPING: 'Đi mua sắm',
            REMOVE_ITEM: 'Xóa sản phẩm',
            UPDATE_CART: 'Cập nhật giỏ hàng',
        },

        FILTERS: {
            FILTER_BY: 'Lọc theo',
            SORT_BY: 'Sắp xếp theo',
            PRICE_RANGE: 'Khoảng giá',
            CATEGORY: 'Danh mục',
            BRAND: 'Thương hiệu',
            RATING: 'Đánh giá',
            CLEAR_FILTERS: 'Xóa bộ lọc',
            APPLY_FILTERS: 'Áp dụng',
            PRICE_LOW_TO_HIGH: 'Giá: Thấp đến cao',
            PRICE_HIGH_TO_LOW: 'Giá: Cao đến thấp',
            NEWEST_FIRST: 'Mới nhất',
            OLDEST_FIRST: 'Cũ nhất',
            BEST_SELLING: 'Bán chạy nhất',
        },
    },

    // Common UI Text
    COMMON: {
        // Actions
        SAVE: 'Lưu',
        CANCEL: 'Hủy',
        DELETE: 'Xóa',
        EDIT: 'Chỉnh sửa',
        VIEW: 'Xem',
        ADD: 'Thêm',
        CREATE: 'Tạo',
        UPDATE: 'Cập nhật',
        REMOVE: 'Xóa bỏ',
        CLOSE: 'Đóng',
        OPEN: 'Mở',
        CONFIRM: 'Xác nhận',
        SUBMIT: 'Gửi',
        RESET: 'Đặt lại',
        CLEAR: 'Xóa',
        SEARCH: 'Tìm kiếm',
        FILTER: 'Lọc',
        SORT: 'Sắp xếp',
        EXPORT: 'Xuất',
        IMPORT: 'Nhập',
        DOWNLOAD: 'Tải xuống',
        UPLOAD: 'Tải lên',
        COPY: 'Sao chép',
        SHARE: 'Chia sẻ',
        PRINT: 'In',
        BACK: 'Quay lại',
        NEXT: 'Tiếp theo',
        PREVIOUS: 'Trước',
        CONTINUE: 'Tiếp tục',
        FINISH: 'Hoàn thành',
        SKIP: 'Bỏ qua',

        // Status
        LOADING: 'Đang tải...',
        SAVING: 'Đang lưu...',
        PROCESSING: 'Đang xử lý...',
        COMPLETED: 'Hoàn thành',
        FAILED: 'Thất bại',
        SUCCESS: 'Thành công',
        ERROR: 'Lỗi',
        WARNING: 'Cảnh báo',
        INFO: 'Thông tin',

        // Data States
        NO_DATA: 'Không có dữ liệu',
        EMPTY_LIST: 'Danh sách trống',
        NO_RESULTS: 'Không tìm thấy kết quả',
        SEARCH_PLACEHOLDER: 'Tìm kiếm...',
        SELECT_PLACEHOLDER: 'Chọn...',

        // Navigation
        HOME: 'Trang chủ',
        DASHBOARD: 'Tổng quan',
        PROFILE: 'Hồ sơ',
        SETTINGS: 'Cài đặt',
        HELP: 'Trợ giúp',
        CONTACT: 'Liên hệ',
        ABOUT: 'Giới thiệu',
        FAQ: 'Câu hỏi thường gặp',
        TERMS: 'Điều khoản',
        PRIVACY: 'Bảo mật',

        // Time
        TODAY: 'Hôm nay',
        YESTERDAY: 'Hôm qua',
        TOMORROW: 'Ngày mai',
        THIS_WEEK: 'Tuần này',
        LAST_WEEK: 'Tuần trước',
        THIS_MONTH: 'Tháng này',
        LAST_MONTH: 'Tháng trước',
        THIS_YEAR: 'Năm nay',

        // Pagination
        PAGE: 'Trang',
        OF: 'của',
        ITEMS_PER_PAGE: 'Mục mỗi trang',
        SHOWING: 'Hiển thị',
        TO: 'đến',
        RESULTS: 'kết quả',

        // File
        CHOOSE_FILE: 'Chọn file',
        DROP_FILE_HERE: 'Thả file vào đây',
        FILE_SELECTED: 'File đã chọn',
        FILE_SIZE: 'Kích thước file',
        FILE_TYPE: 'Loại file',
        MAX_FILE_SIZE: 'Kích thước tối đa',
        SUPPORTED_FORMATS: 'Định dạng hỗ trợ',

        // Confirmation
        ARE_YOU_SURE: 'Bạn có chắc chắn?',
        THIS_ACTION_CANNOT_BE_UNDONE: 'Hành động này không thể hoàn tác',
        YES_DELETE: 'Có, xóa',
        YES_CONFIRM: 'Có, xác nhận',
        NO_CANCEL: 'Không, hủy',
    },
} as const;
